/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package irestads.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import irestads.model.SinhVien;

import irestads.service.LopLocalService;
import irestads.service.LopService;
import irestads.service.SinhVienLocalService;
import irestads.service.SinhVienService;

import irestads.service.persistence.LopPersistence;
import irestads.service.persistence.SinhVienPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the sinh vien local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link irestads.service.impl.SinhVienLocalServiceImpl}.
 * </p>
 *
 * @author ADMIN
 * @see irestads.service.impl.SinhVienLocalServiceImpl
 * @see irestads.service.SinhVienLocalServiceUtil
 * @generated
 */
public abstract class SinhVienLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements SinhVienLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link irestads.service.SinhVienLocalServiceUtil} to access the sinh vien local service.
	 */

	/**
	 * Adds the sinh vien to the database. Also notifies the appropriate model listeners.
	 *
	 * @param sinhVien the sinh vien
	 * @return the sinh vien that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public SinhVien addSinhVien(SinhVien sinhVien) throws SystemException {
		sinhVien.setNew(true);

		return sinhVienPersistence.update(sinhVien, false);
	}

	/**
	 * Creates a new sinh vien with the primary key. Does not add the sinh vien to the database.
	 *
	 * @param sinhVienId the primary key for the new sinh vien
	 * @return the new sinh vien
	 */
	public SinhVien createSinhVien(long sinhVienId) {
		return sinhVienPersistence.create(sinhVienId);
	}

	/**
	 * Deletes the sinh vien with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param sinhVienId the primary key of the sinh vien
	 * @return the sinh vien that was removed
	 * @throws PortalException if a sinh vien with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public SinhVien deleteSinhVien(long sinhVienId)
		throws PortalException, SystemException {
		return sinhVienPersistence.remove(sinhVienId);
	}

	/**
	 * Deletes the sinh vien from the database. Also notifies the appropriate model listeners.
	 *
	 * @param sinhVien the sinh vien
	 * @return the sinh vien that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public SinhVien deleteSinhVien(SinhVien sinhVien) throws SystemException {
		return sinhVienPersistence.remove(sinhVien);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(SinhVien.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return sinhVienPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return sinhVienPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return sinhVienPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return sinhVienPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public SinhVien fetchSinhVien(long sinhVienId) throws SystemException {
		return sinhVienPersistence.fetchByPrimaryKey(sinhVienId);
	}

	/**
	 * Returns the sinh vien with the primary key.
	 *
	 * @param sinhVienId the primary key of the sinh vien
	 * @return the sinh vien
	 * @throws PortalException if a sinh vien with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public SinhVien getSinhVien(long sinhVienId)
		throws PortalException, SystemException {
		return sinhVienPersistence.findByPrimaryKey(sinhVienId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return sinhVienPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the sinh viens.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of sinh viens
	 * @param end the upper bound of the range of sinh viens (not inclusive)
	 * @return the range of sinh viens
	 * @throws SystemException if a system exception occurred
	 */
	public List<SinhVien> getSinhViens(int start, int end)
		throws SystemException {
		return sinhVienPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of sinh viens.
	 *
	 * @return the number of sinh viens
	 * @throws SystemException if a system exception occurred
	 */
	public int getSinhViensCount() throws SystemException {
		return sinhVienPersistence.countAll();
	}

	/**
	 * Updates the sinh vien in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param sinhVien the sinh vien
	 * @return the sinh vien that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public SinhVien updateSinhVien(SinhVien sinhVien) throws SystemException {
		return updateSinhVien(sinhVien, true);
	}

	/**
	 * Updates the sinh vien in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param sinhVien the sinh vien
	 * @param merge whether to merge the sinh vien with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the sinh vien that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public SinhVien updateSinhVien(SinhVien sinhVien, boolean merge)
		throws SystemException {
		sinhVien.setNew(false);

		return sinhVienPersistence.update(sinhVien, merge);
	}

	/**
	 * Returns the lop local service.
	 *
	 * @return the lop local service
	 */
	public LopLocalService getLopLocalService() {
		return lopLocalService;
	}

	/**
	 * Sets the lop local service.
	 *
	 * @param lopLocalService the lop local service
	 */
	public void setLopLocalService(LopLocalService lopLocalService) {
		this.lopLocalService = lopLocalService;
	}

	/**
	 * Returns the lop remote service.
	 *
	 * @return the lop remote service
	 */
	public LopService getLopService() {
		return lopService;
	}

	/**
	 * Sets the lop remote service.
	 *
	 * @param lopService the lop remote service
	 */
	public void setLopService(LopService lopService) {
		this.lopService = lopService;
	}

	/**
	 * Returns the lop persistence.
	 *
	 * @return the lop persistence
	 */
	public LopPersistence getLopPersistence() {
		return lopPersistence;
	}

	/**
	 * Sets the lop persistence.
	 *
	 * @param lopPersistence the lop persistence
	 */
	public void setLopPersistence(LopPersistence lopPersistence) {
		this.lopPersistence = lopPersistence;
	}

	/**
	 * Returns the sinh vien local service.
	 *
	 * @return the sinh vien local service
	 */
	public SinhVienLocalService getSinhVienLocalService() {
		return sinhVienLocalService;
	}

	/**
	 * Sets the sinh vien local service.
	 *
	 * @param sinhVienLocalService the sinh vien local service
	 */
	public void setSinhVienLocalService(
		SinhVienLocalService sinhVienLocalService) {
		this.sinhVienLocalService = sinhVienLocalService;
	}

	/**
	 * Returns the sinh vien remote service.
	 *
	 * @return the sinh vien remote service
	 */
	public SinhVienService getSinhVienService() {
		return sinhVienService;
	}

	/**
	 * Sets the sinh vien remote service.
	 *
	 * @param sinhVienService the sinh vien remote service
	 */
	public void setSinhVienService(SinhVienService sinhVienService) {
		this.sinhVienService = sinhVienService;
	}

	/**
	 * Returns the sinh vien persistence.
	 *
	 * @return the sinh vien persistence
	 */
	public SinhVienPersistence getSinhVienPersistence() {
		return sinhVienPersistence;
	}

	/**
	 * Sets the sinh vien persistence.
	 *
	 * @param sinhVienPersistence the sinh vien persistence
	 */
	public void setSinhVienPersistence(SinhVienPersistence sinhVienPersistence) {
		this.sinhVienPersistence = sinhVienPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("irestads.model.SinhVien",
			sinhVienLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"irestads.model.SinhVien");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return SinhVien.class;
	}

	protected String getModelClassName() {
		return SinhVien.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = sinhVienPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = LopLocalService.class)
	protected LopLocalService lopLocalService;
	@BeanReference(type = LopService.class)
	protected LopService lopService;
	@BeanReference(type = LopPersistence.class)
	protected LopPersistence lopPersistence;
	@BeanReference(type = SinhVienLocalService.class)
	protected SinhVienLocalService sinhVienLocalService;
	@BeanReference(type = SinhVienService.class)
	protected SinhVienService sinhVienService;
	@BeanReference(type = SinhVienPersistence.class)
	protected SinhVienPersistence sinhVienPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private SinhVienLocalServiceClpInvoker _clpInvoker = new SinhVienLocalServiceClpInvoker();
}