/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package irestads.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SinhVien service. Represents a row in the &quot;testprimeface_SinhVien&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link irestads.model.impl.SinhVienModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link irestads.model.impl.SinhVienImpl}.
 * </p>
 *
 * @author ADMIN
 * @see SinhVien
 * @see irestads.model.impl.SinhVienImpl
 * @see irestads.model.impl.SinhVienModelImpl
 * @generated
 */
public interface SinhVienModel extends BaseModel<SinhVien> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sinh vien model instance should use the {@link SinhVien} interface instead.
	 */

	/**
	 * Returns the primary key of this sinh vien.
	 *
	 * @return the primary key of this sinh vien
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sinh vien.
	 *
	 * @param primaryKey the primary key of this sinh vien
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sinh vien ID of this sinh vien.
	 *
	 * @return the sinh vien ID of this sinh vien
	 */
	public long getSinhVienId();

	/**
	 * Sets the sinh vien ID of this sinh vien.
	 *
	 * @param sinhVienId the sinh vien ID of this sinh vien
	 */
	public void setSinhVienId(long sinhVienId);

	/**
	 * Returns the mssv of this sinh vien.
	 *
	 * @return the mssv of this sinh vien
	 */
	@AutoEscape
	public String getMssv();

	/**
	 * Sets the mssv of this sinh vien.
	 *
	 * @param mssv the mssv of this sinh vien
	 */
	public void setMssv(String mssv);

	/**
	 * Returns the ten of this sinh vien.
	 *
	 * @return the ten of this sinh vien
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this sinh vien.
	 *
	 * @param ten the ten of this sinh vien
	 */
	public void setTen(String ten);

	/**
	 * Returns the dia chi of this sinh vien.
	 *
	 * @return the dia chi of this sinh vien
	 */
	@AutoEscape
	public String getDiaChi();

	/**
	 * Sets the dia chi of this sinh vien.
	 *
	 * @param diaChi the dia chi of this sinh vien
	 */
	public void setDiaChi(String diaChi);

	/**
	 * Returns the diem of this sinh vien.
	 *
	 * @return the diem of this sinh vien
	 */
	public double getDiem();

	/**
	 * Sets the diem of this sinh vien.
	 *
	 * @param diem the diem of this sinh vien
	 */
	public void setDiem(double diem);

	/**
	 * Returns the lop ID of this sinh vien.
	 *
	 * @return the lop ID of this sinh vien
	 */
	@AutoEscape
	public String getLopId();

	/**
	 * Sets the lop ID of this sinh vien.
	 *
	 * @param lopId the lop ID of this sinh vien
	 */
	public void setLopId(String lopId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SinhVien sinhVien);

	public int hashCode();

	public CacheModel<SinhVien> toCacheModel();

	public SinhVien toEscapedModel();

	public String toString();

	public String toXmlString();
}