/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package irestads.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import irestads.model.Menu;
import irestads.model.MenuModel;
import irestads.model.MenuSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Menu service. Represents a row in the &quot;dishsstore_Menu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link irestads.model.MenuModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MenuImpl}.
 * </p>
 *
 * @author Be
 * @see MenuImpl
 * @see irestads.model.Menu
 * @see irestads.model.MenuModel
 * @generated
 */
@JSON(strict = true)
public class MenuModelImpl extends BaseModelImpl<Menu> implements MenuModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a menu model instance should use the {@link irestads.model.Menu} interface instead.
	 */
	public static final String TABLE_NAME = "dishsstore_Menu";
	public static final Object[][] TABLE_COLUMNS = {
			{ "menuId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "menuName", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table dishsstore_Menu (menuId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,menuName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table dishsstore_Menu";
	public static final String ORDER_BY_JPQL = " ORDER BY menu.menuName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY dishsstore_Menu.menuName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.irestads.model.Menu"), true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.irestads.model.Menu"), true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.irestads.model.Menu"), true);
	public static long MENUNAME_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Menu toModel(MenuSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Menu model = new MenuImpl();

		model.setMenuId(soapModel.getMenuId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setMenuName(soapModel.getMenuName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Menu> toModels(MenuSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Menu> models = new ArrayList<Menu>(soapModels.length);

		for (MenuSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.irestads.model.Menu"));

	public MenuModelImpl() {
	}

	public long getPrimaryKey() {
		return _menuId;
	}

	public void setPrimaryKey(long primaryKey) {
		setMenuId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_menuId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Menu.class;
	}

	public String getModelClassName() {
		return Menu.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("menuId", getMenuId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("menuName", getMenuName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long menuId = (Long)attributes.get("menuId");

		if (menuId != null) {
			setMenuId(menuId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String menuName = (String)attributes.get("menuName");

		if (menuName != null) {
			setMenuName(menuName);
		}
	}

	@JSON
	public long getMenuId() {
		return _menuId;
	}

	public void setMenuId(long menuId) {
		_menuId = menuId;
	}

	@JSON
	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public String getMenuName() {
		if (_menuName == null) {
			return StringPool.BLANK;
		}
		else {
			return _menuName;
		}
	}

	public void setMenuName(String menuName) {
		_columnBitmask = -1L;

		if (_originalMenuName == null) {
			_originalMenuName = _menuName;
		}

		_menuName = menuName;
	}

	public String getOriginalMenuName() {
		return GetterUtil.getString(_originalMenuName);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Menu.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Menu toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Menu)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		MenuImpl menuImpl = new MenuImpl();

		menuImpl.setMenuId(getMenuId());
		menuImpl.setCompanyId(getCompanyId());
		menuImpl.setUserId(getUserId());
		menuImpl.setUserName(getUserName());
		menuImpl.setCreateDate(getCreateDate());
		menuImpl.setModifiedDate(getModifiedDate());
		menuImpl.setMenuName(getMenuName());

		menuImpl.resetOriginalValues();

		return menuImpl;
	}

	public int compareTo(Menu menu) {
		int value = 0;

		value = getMenuName().compareTo(menu.getMenuName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Menu menu = null;

		try {
			menu = (Menu)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = menu.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		MenuModelImpl menuModelImpl = this;

		menuModelImpl._originalMenuName = menuModelImpl._menuName;

		menuModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Menu> toCacheModel() {
		MenuCacheModel menuCacheModel = new MenuCacheModel();

		menuCacheModel.menuId = getMenuId();

		menuCacheModel.companyId = getCompanyId();

		menuCacheModel.userId = getUserId();

		menuCacheModel.userName = getUserName();

		String userName = menuCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			menuCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			menuCacheModel.createDate = createDate.getTime();
		}
		else {
			menuCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			menuCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			menuCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		menuCacheModel.menuName = getMenuName();

		String menuName = menuCacheModel.menuName;

		if ((menuName != null) && (menuName.length() == 0)) {
			menuCacheModel.menuName = null;
		}

		return menuCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{menuId=");
		sb.append(getMenuId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", menuName=");
		sb.append(getMenuName());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("irestads.model.Menu");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>menuId</column-name><column-value><![CDATA[");
		sb.append(getMenuId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>menuName</column-name><column-value><![CDATA[");
		sb.append(getMenuName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Menu.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Menu.class
		};
	private long _menuId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _menuName;
	private String _originalMenuName;
	private long _columnBitmask;
	private Menu _escapedModelProxy;
}