/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package irestads.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AdsItem service. Represents a row in the &quot;dishsstore_AdsItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link irestads.model.impl.AdsItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link irestads.model.impl.AdsItemImpl}.
 * </p>
 *
 * @author Be
 * @see AdsItem
 * @see irestads.model.impl.AdsItemImpl
 * @see irestads.model.impl.AdsItemModelImpl
 * @generated
 */
public interface AdsItemModel extends AuditedModel, BaseModel<AdsItem> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ads item model instance should use the {@link AdsItem} interface instead.
	 */

	/**
	 * Returns the primary key of this ads item.
	 *
	 * @return the primary key of this ads item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ads item.
	 *
	 * @param primaryKey the primary key of this ads item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ads item ID of this ads item.
	 *
	 * @return the ads item ID of this ads item
	 */
	public long getAdsItemId();

	/**
	 * Sets the ads item ID of this ads item.
	 *
	 * @param adsItemId the ads item ID of this ads item
	 */
	public void setAdsItemId(long adsItemId);

	/**
	 * Returns the company ID of this ads item.
	 *
	 * @return the company ID of this ads item
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this ads item.
	 *
	 * @param companyId the company ID of this ads item
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ads item.
	 *
	 * @return the user ID of this ads item
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this ads item.
	 *
	 * @param userId the user ID of this ads item
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ads item.
	 *
	 * @return the user uuid of this ads item
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this ads item.
	 *
	 * @param userUuid the user uuid of this ads item
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ads item.
	 *
	 * @return the user name of this ads item
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this ads item.
	 *
	 * @param userName the user name of this ads item
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ads item.
	 *
	 * @return the create date of this ads item
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ads item.
	 *
	 * @param createDate the create date of this ads item
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ads item.
	 *
	 * @return the modified date of this ads item
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ads item.
	 *
	 * @param modifiedDate the modified date of this ads item
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the company name of this ads item.
	 *
	 * @return the company name of this ads item
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this ads item.
	 *
	 * @param companyName the company name of this ads item
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the product name of this ads item.
	 *
	 * @return the product name of this ads item
	 */
	@AutoEscape
	public String getProductName();

	/**
	 * Sets the product name of this ads item.
	 *
	 * @param productName the product name of this ads item
	 */
	public void setProductName(String productName);

	/**
	 * Returns the number phone of this ads item.
	 *
	 * @return the number phone of this ads item
	 */
	@AutoEscape
	public String getNumberPhone();

	/**
	 * Sets the number phone of this ads item.
	 *
	 * @param numberPhone the number phone of this ads item
	 */
	public void setNumberPhone(String numberPhone);

	/**
	 * Returns the email of this ads item.
	 *
	 * @return the email of this ads item
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this ads item.
	 *
	 * @param email the email of this ads item
	 */
	public void setEmail(String email);

	/**
	 * Returns the address of this ads item.
	 *
	 * @return the address of this ads item
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this ads item.
	 *
	 * @param address the address of this ads item
	 */
	public void setAddress(String address);

	/**
	 * Returns the facebook of this ads item.
	 *
	 * @return the facebook of this ads item
	 */
	@AutoEscape
	public String getFacebook();

	/**
	 * Sets the facebook of this ads item.
	 *
	 * @param facebook the facebook of this ads item
	 */
	public void setFacebook(String facebook);

	/**
	 * Returns the twitter of this ads item.
	 *
	 * @return the twitter of this ads item
	 */
	@AutoEscape
	public String getTwitter();

	/**
	 * Sets the twitter of this ads item.
	 *
	 * @param twitter the twitter of this ads item
	 */
	public void setTwitter(String twitter);

	/**
	 * Returns the description of this ads item.
	 *
	 * @return the description of this ads item
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this ads item.
	 *
	 * @param description the description of this ads item
	 */
	public void setDescription(String description);

	/**
	 * Returns the image content of this ads item.
	 *
	 * @return the image content of this ads item
	 */
	@AutoEscape
	public String getImageContent();

	/**
	 * Sets the image content of this ads item.
	 *
	 * @param imageContent the image content of this ads item
	 */
	public void setImageContent(String imageContent);

	/**
	 * Returns the time during of this ads item.
	 *
	 * @return the time during of this ads item
	 */
	public int getTimeDuring();

	/**
	 * Sets the time during of this ads item.
	 *
	 * @param timeDuring the time during of this ads item
	 */
	public void setTimeDuring(int timeDuring);

	/**
	 * Returns the tags of this ads item.
	 *
	 * @return the tags of this ads item
	 */
	@AutoEscape
	public String getTags();

	/**
	 * Sets the tags of this ads item.
	 *
	 * @param tags the tags of this ads item
	 */
	public void setTags(String tags);

	/**
	 * Returns the item type of this ads item.
	 *
	 * @return the item type of this ads item
	 */
	@AutoEscape
	public String getItemType();

	/**
	 * Sets the item type of this ads item.
	 *
	 * @param itemType the item type of this ads item
	 */
	public void setItemType(String itemType);

	/**
	 * Returns the category ads ID of this ads item.
	 *
	 * @return the category ads ID of this ads item
	 */
	public long getCategoryAdsId();

	/**
	 * Sets the category ads ID of this ads item.
	 *
	 * @param categoryAdsId the category ads ID of this ads item
	 */
	public void setCategoryAdsId(long categoryAdsId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AdsItem adsItem);

	public int hashCode();

	public CacheModel<AdsItem> toCacheModel();

	public AdsItem toEscapedModel();

	public String toString();

	public String toXmlString();
}