/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package irestads.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CategoryAds service. Represents a row in the &quot;dishsstore_CategoryAds&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link irestads.model.impl.CategoryAdsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link irestads.model.impl.CategoryAdsImpl}.
 * </p>
 *
 * @author Be
 * @see CategoryAds
 * @see irestads.model.impl.CategoryAdsImpl
 * @see irestads.model.impl.CategoryAdsModelImpl
 * @generated
 */
public interface CategoryAdsModel extends AuditedModel, BaseModel<CategoryAds> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a category ads model instance should use the {@link CategoryAds} interface instead.
	 */

	/**
	 * Returns the primary key of this category ads.
	 *
	 * @return the primary key of this category ads
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this category ads.
	 *
	 * @param primaryKey the primary key of this category ads
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the category ads ID of this category ads.
	 *
	 * @return the category ads ID of this category ads
	 */
	public long getCategoryAdsId();

	/**
	 * Sets the category ads ID of this category ads.
	 *
	 * @param categoryAdsId the category ads ID of this category ads
	 */
	public void setCategoryAdsId(long categoryAdsId);

	/**
	 * Returns the company ID of this category ads.
	 *
	 * @return the company ID of this category ads
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this category ads.
	 *
	 * @param companyId the company ID of this category ads
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this category ads.
	 *
	 * @return the user ID of this category ads
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this category ads.
	 *
	 * @param userId the user ID of this category ads
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this category ads.
	 *
	 * @return the user uuid of this category ads
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this category ads.
	 *
	 * @param userUuid the user uuid of this category ads
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this category ads.
	 *
	 * @return the user name of this category ads
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this category ads.
	 *
	 * @param userName the user name of this category ads
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this category ads.
	 *
	 * @return the create date of this category ads
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this category ads.
	 *
	 * @param createDate the create date of this category ads
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this category ads.
	 *
	 * @return the modified date of this category ads
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this category ads.
	 *
	 * @param modifiedDate the modified date of this category ads
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the category ads name of this category ads.
	 *
	 * @return the category ads name of this category ads
	 */
	@AutoEscape
	public String getCategoryAdsName();

	/**
	 * Sets the category ads name of this category ads.
	 *
	 * @param categoryAdsName the category ads name of this category ads
	 */
	public void setCategoryAdsName(String categoryAdsName);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CategoryAds categoryAds);

	public int hashCode();

	public CacheModel<CategoryAds> toCacheModel();

	public CategoryAds toEscapedModel();

	public String toString();

	public String toXmlString();
}