/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package irestads.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Lop service. Represents a row in the &quot;testprimeface_Lop&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link irestads.model.impl.LopModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link irestads.model.impl.LopImpl}.
 * </p>
 *
 * @author ADMIN
 * @see Lop
 * @see irestads.model.impl.LopImpl
 * @see irestads.model.impl.LopModelImpl
 * @generated
 */
public interface LopModel extends BaseModel<Lop> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lop model instance should use the {@link Lop} interface instead.
	 */

	/**
	 * Returns the primary key of this lop.
	 *
	 * @return the primary key of this lop
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lop.
	 *
	 * @param primaryKey the primary key of this lop
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lop ID of this lop.
	 *
	 * @return the lop ID of this lop
	 */
	public long getLopId();

	/**
	 * Sets the lop ID of this lop.
	 *
	 * @param lopId the lop ID of this lop
	 */
	public void setLopId(long lopId);

	/**
	 * Returns the ten lop of this lop.
	 *
	 * @return the ten lop of this lop
	 */
	@AutoEscape
	public String getTenLop();

	/**
	 * Sets the ten lop of this lop.
	 *
	 * @param tenLop the ten lop of this lop
	 */
	public void setTenLop(String tenLop);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Lop lop);

	public int hashCode();

	public CacheModel<Lop> toCacheModel();

	public Lop toEscapedModel();

	public String toString();

	public String toXmlString();
}