package irestads.beans;


import irestads.model.Dish;


import irestads.service.DishServiceUtil;



import java.io.Serializable;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import javax.faces.application.FacesMessage;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import org.primefaces.event.RowEditEvent;



public class DishBeans implements Serializable {
	private List<Dish> dishs;
	private Dish dishSelected;
	private String searchType;
	private String keyWords;
	
	//Generated by Map search types
		private static Map<String,Object> searchTypesValue;
		static{
			searchTypesValue = new LinkedHashMap<String,Object>();
			searchTypesValue.put("Tất cả", "0"); //label, value
			searchTypesValue.put("Mã món ăn", "1"); //label, value
			searchTypesValue.put("Tên món ăn", "2"); //label, value
			searchTypesValue.put("", ""); //label, value
			searchTypesValue.put("", ""); //label, value
		}
	 
		
	public DishBeans() {
		this.dishs = new ArrayList<Dish>();
		this.getDishsFromDB();
		// TODO Auto-generated constructor stub
	}
	public void onEdit(RowEditEvent event) {
		try {
			Dish dish = (Dish) event.getObject();
			dish = DishServiceUtil.updateDish(dish);
			String message = "Không thể thực hiện thay đổi thông tin món ăn";
			if (dish != null) {
				message = "Đã thay đổi thông tin món ăn thành công";
				this.getDishsFromDB();
			}
			FacesMessage msg = new FacesMessage(message, dish.getDishId()+ " : "+
				dish.getDishName());
			FacesContext.getCurrentInstance().addMessage(null, msg);
			
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		
	}
	
	public List<Dish> getDishs() {

		
		    return dishs;
	
	}


	public void setDishs(List<Dish> dishs) {
		this.dishs = dishs;
	}


	public Dish getDishSelected() {
		return dishSelected;
	}


	public void setDishSelected(Dish dishSelected) {
		this.dishSelected = dishSelected;
	}


	public List<Dish> getDishsFromDB(){
		this.dishs= DishServiceUtil.getAllDishs();
		//System.out.println("get dishs ------------------"+dishs.size());
		return this.dishs;
		
	}
	public void deleteDish(){
		
		Dish dish=DishServiceUtil.deleteDish(dishSelected);
		String message = "Không thể thực hiện xóa sinh viên";
		if (dish != null) {
			message = "Đã xóa sinh viên thành công";
			this.getDishsFromDB();
		}
		FacesMessage msg = new FacesMessage(message, dish.getDishId() + " : "
				+ dish.getDishName());
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}
	public void onCancel(RowEditEvent event) {  
        FacesMessage msg = new FacesMessage("Car Cancelled", ((Dish) event.getObject()).getDishName());  
  
        FacesContext.getCurrentInstance().addMessage(null, msg);  
    }  

	

	public String getSearchType() {
			return searchType;
		}
		public void setSearchType(String searchType) {
			this.searchType = searchType;
		}
		public String getKeyWords() {
			return keyWords;
		}
		public void setKeyWords(String keyWords) {
			this.keyWords = keyWords;
		}
		public static Map<String, Object> getSearchTypesValue() {
			return searchTypesValue;
		}
		public static void setSearchTypesValue(Map<String, Object> searchTypesValue) {
			DishBeans.searchTypesValue = searchTypesValue;
		}


}
