/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package irestads.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TestEntity service. Represents a row in the &quot;testws_TestEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link irestads.model.impl.TestEntityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link irestads.model.impl.TestEntityImpl}.
 * </p>
 *
 * @author ADMIN
 * @see TestEntity
 * @see irestads.model.impl.TestEntityImpl
 * @see irestads.model.impl.TestEntityModelImpl
 * @generated
 */
public interface TestEntityModel extends AuditedModel, BaseModel<TestEntity> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a test entity model instance should use the {@link TestEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this test entity.
	 *
	 * @return the primary key of this test entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this test entity.
	 *
	 * @param primaryKey the primary key of this test entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entity ID of this test entity.
	 *
	 * @return the entity ID of this test entity
	 */
	public long getEntityId();

	/**
	 * Sets the entity ID of this test entity.
	 *
	 * @param entityId the entity ID of this test entity
	 */
	public void setEntityId(long entityId);

	/**
	 * Returns the company ID of this test entity.
	 *
	 * @return the company ID of this test entity
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this test entity.
	 *
	 * @param companyId the company ID of this test entity
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this test entity.
	 *
	 * @return the user ID of this test entity
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this test entity.
	 *
	 * @param userId the user ID of this test entity
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this test entity.
	 *
	 * @return the user uuid of this test entity
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this test entity.
	 *
	 * @param userUuid the user uuid of this test entity
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this test entity.
	 *
	 * @return the user name of this test entity
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this test entity.
	 *
	 * @param userName the user name of this test entity
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this test entity.
	 *
	 * @return the create date of this test entity
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this test entity.
	 *
	 * @param createDate the create date of this test entity
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this test entity.
	 *
	 * @return the modified date of this test entity
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this test entity.
	 *
	 * @param modifiedDate the modified date of this test entity
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this test entity.
	 *
	 * @return the name of this test entity
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this test entity.
	 *
	 * @param name the name of this test entity
	 */
	public void setName(String name);

	/**
	 * Returns the pass of this test entity.
	 *
	 * @return the pass of this test entity
	 */
	@AutoEscape
	public String getPass();

	/**
	 * Sets the pass of this test entity.
	 *
	 * @param pass the pass of this test entity
	 */
	public void setPass(String pass);

	/**
	 * Returns the email of this test entity.
	 *
	 * @return the email of this test entity
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this test entity.
	 *
	 * @param email the email of this test entity
	 */
	public void setEmail(String email);

	/**
	 * Returns the login date of this test entity.
	 *
	 * @return the login date of this test entity
	 */
	public Date getLoginDate();

	/**
	 * Sets the login date of this test entity.
	 *
	 * @param loginDate the login date of this test entity
	 */
	public void setLoginDate(Date loginDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TestEntity testEntity);

	public int hashCode();

	public CacheModel<TestEntity> toCacheModel();

	public TestEntity toEscapedModel();

	public String toString();

	public String toXmlString();
}